# Generated by Django 3.2.9 on 2021-11-13 00:47

from django.db import migrations, models
import petRegister.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pergunta', models.TextField()),
                ('Resposta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PetRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomePet', models.CharField(max_length=100)),
                ('Idade', models.IntegerField()),
                ('Sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], default='M', max_length=1)),
                ('Porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='M', max_length=1)),
                ('Imagem', models.ImageField(blank=True, null=True, upload_to=petRegister.models.upload_imagem_pet)),
                ('Especie', models.CharField(max_length=100)),
                ('btCastrado', models.BooleanField()),
                ('btVacinado', models.BooleanField()),
                ('btVermifugado', models.BooleanField()),
                ('DescricaoAnimal', models.TextField()),
                ('bitDoador', models.BooleanField()),
            ],
        ),
    ]
