# Generated by Django 3.2.8 on 2021-11-12 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import petRegister.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetRegistro',
            fields=[
                ('Pet_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NomePet', models.CharField(max_length=100)),
                ('Idade', models.IntegerField()),
                ('Sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], default='M', max_length=1)),
                ('Porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='M', max_length=1)),
                ('Imagem', models.ImageField(blank=True, null=True, upload_to=petRegister.models.upload_imagem_pet)),
                ('Especie', models.CharField(max_length=100)),
                ('btCastrado', models.BooleanField()),
                ('btVacinado', models.BooleanField()),
                ('btVermifugado', models.BooleanField()),
                ('DescricaoAnimal', models.TextField()),
                ('bitDoador', models.BooleanField()),
                ('Usuario_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemPet',
            fields=[
                ('ID_Pergunta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Pergunta', models.TextField()),
                ('Resposta', models.TextField()),
                ('Id_Pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petRegister.petregistro')),
            ],
        ),
    ]
