# Generated by Django 3.2.9 on 2021-11-13 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petRegister', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petregistro',
            name='id_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagempet',
            name='Id_Pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petRegister.petregistro'),
        ),
    ]
